---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: log
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: elasticsearch
  chart:
    repository: https://helm.elastic.co
    name: elasticsearch
    version: 7.7.0
    helmVersion: v3
  values:
    resources:
      requests:
        cpu: "250m"
        memory: "2Gi"
      limits:
        cpu: "250m"
        memory: "2Gi"
  