---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: jenkins
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: jenkins
    version: 1.27.0
    helmVersion: v3
  values:
    master:
      admin:
        existingSecret: jenkins-credentials
        userKey: jenkins-user
        passwordKey: jenkins-password
      installPlugins:
        - kubernetes:latest
        - workflow-job:latest
        - workflow-aggregator:latest
        - credentials-binding:latest
        - git:latest
        - google-oauth-plugin:latest
        - google-source-plugin:latest
        - google-kubernetes-engine:latest
        - google-storage-plugin:latest
        - google-container-registry-auth:latest
        - docker-build-step:latest
        - docker-workflow:latest
      resources:
        requests:
          cpu: "50m"
          memory: "1024Mi"
        limits:
          cpu: "1"
          memory: "3500Mi"
      javaOpts: "-Xms3500m -Xmx3500m"
      serviceType: ClusterIP
    agent:
      resources:
        requests:
          cpu: "500m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
    persistence:
      size: 100Gi
  